server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

rabbitmq:
  queue:
    order-paid: notification-service.order.paid.queue
    order-created: notification-service.order.created.queue
    user-activity: user-activity.notification.queue