version: '3.8'
services:
  redis:
    image: redis:7
    container_name: user-redis
    ports:
      - "6379:6379"

  gateway-redis:
    image: redis:7
    container_name: gateway-redis
    ports:
      - "6380:6379"
  
  postgres:
    image: postgres:17
    container_name: user-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
  
  product-postgres:
    image: postgres:17
    container_name: product-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: product_db    
    ports:
      - "5433:5432"

  order-postgres:
    image: postgres:17
    container_name: order-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: order_db    
    ports:
      - "5434:5432"

  payment-postgres:
    image: postgres:17
    container_name: payment-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: payment_db    
    ports:
      - "5435:5432"  
      
  review-postgres:
    image: postgres:17
    container_name: review-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: review_db    
    ports:
      - "5436:5432"              
  
  minio:
    image: minio/minio:latest
    container_name: product-minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

volumes:
  minio_data: