server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: marketplace_user
    password: javak
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


yookassa:
  key: test_SYj0uyikXLW6VivwdkFTg4mPOpw6keu6YA-LadahdCw
  shopId: 1310021

internal:
  secret-token: klintcy_dodge


