server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

services:
  user-service: ${USER_SERVICE_URL:http://localhost:8081}
  product-service: ${PRODUCT_SERVICE_URL:http://localhost:8082}
  order-service: ${ORDER_SERVICE_URL:http://localhost:8083}
  payment-service: ${PAYMENT_SERVICE_URL:http://localhost:8084}
  admin-service: ${ADMIN_SERVICE_URL:http://localhost:8089}
  review-service: ${REVIEW_SERVICE_URL:http://localhost:8088}
  search-service: ${SEARCH_SERVICE_URL:http://localhost:8086}

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 2000ms
          multiplier: 3.0
          max-interval: 300000ms

rabbitmq:
  queue:
    order: order-service.payment.queue
    dead: dead.letter.queue

minio:
  bucket: products

internal:
  secret-token: ${INTERNAL_SECRET_TOKEN}