spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: marketplace_user
    password: javak

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

jwt:
  secret: iBpYBZkfDtYPnHSwC9S5oGAWj2CMfeslvZq0xHVvHlA=
  expiration: 86400000
  refresh: DBRLGhhHxbucmMbCNATFGbiJmI+Hsops3q+Z/oZapds=
  refresh-expiration: 604800000

internal:
  secret-token: klintcy_dodge

services:
  user-service:
    url: http://localhost:8080

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: products

rabbitmq:
  queue:
    product: product-service.review.queue


