server:
    port: 8088

spring:
    datasource:
        url: jdbc:postgresql://localhost:5436/review_db
        username: marketplace_user
        password: javak
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: products