server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: search-service

rabbitmq:
  queue:
    product: search-service.product.queue

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: DEBUG